import csv
from pathlib import Path

csv_path = Path('ml_classification_input_updated.csv')

exception_map = {
'c30000680':'AssertionError: IDCS editor template HTML not as expected',
'c29996023':'AssertionError: Cell vertical alignment updated beyond target cell',
'c29996022':'AssertionError: Cell vertical alignment updated beyond target cell',
'c29996030':'AssertionError: Cell vertical alignment updated beyond target cell',
'c29996027':'AssertionError: Cell horizontal alignment updated beyond target cell',
'c29996028':'AssertionError: Cell horizontal alignment updated beyond target cell',
'c29996029':'AssertionError: Cell horizontal alignment updated beyond target cell',
'c30000681':'AssertionError: IDCS editor template HTML not as expected',
'c29996031':'AssertionError: Cell vertical alignment updated beyond target cell',
'c30000682':'AssertionError: IDCS editor template HTML not as expected',
'c29996021':'AssertionError: Cell vertical alignment updated beyond target cell',
'c29868427':'AssertionError: Expected template was not filtered',
'c19926499':'NoSuchElementException: expected editor text node not found',
'c29996013':'AssertionError: table not as expected after inserting rows',
'c30093696':'AssertionError: effective retention rate variable formatting incorrect',
'c29996026':'AssertionError: Cell horizontal alignment updated beyond target cell',
'c29996032':'AssertionError: Cell vertical alignment updated beyond target cell',
'c879898':'AttributeError: DisplayDate has no attribute french_translation',
'c1119122':'StaleElementReferenceException: stale element not found',
'c29647310':'StaleElementReferenceException: stale element not found',
'c29759993':'AssertionError: Disable Owner Billing link is present',
'c29986480':'AssertionError: signed UCLW document content incorrect',
'c879904':'AttributeError: DisplayDate has no attribute french_translation',
'c879894':'AttributeError: DisplayDate has no attribute french_translation',
'c879903':'AttributeError: DisplayDate has no attribute french_translation',
'c879901':'AttributeError: DisplayDate has no attribute french_translation',
'c879902':'AttributeError: DisplayDate has no attribute french_translation',
'c879900':'AttributeError: DisplayDate has no attribute french_translation',
'c879899':'AttributeError: DisplayDate has no attribute french_translation',
'c20904245':'RuntimeException: Edit e-Sign PIN link not clickable',
'c20904268':'RuntimeException: Edit e-Sign PIN link not clickable',
'c472573':'RuntimeException: Edit e-Sign PIN link not clickable',
'c2505467':'NoSuchElementException: report-name input not found',
'c30087463':'NoSuchElementException: createReportSelectAll_programs input not found',
'c30095456':'NoSuchElementException: createReportSelectAll_programs input not found',
'c8370199':'AssertionError: toast message indicating draw reopened not present',
'c29986467':'AssertionError: signed subs UCLW content on first draw incorrect',
'c30096980':'RuntimeException: select all programs control not clickable',
'c879897':'AttributeError: DisplayDate has no attribute french_translation',
'c18205514':'AssertionError: Empty report should be generated',
'c29986466':'AssertionError: signed subs CLW content on final draw incorrect',
'c15724980':'RuntimeException: notification link not clickable in Messages',
'c27276649':'AssertionError: unsigned document should get downloaded',
'c1156161':'AssertionError: FeeBill refund/payment values not as expected',
'c29995857':'AssertionError: blank table in editor not present',
'c209985':'AssertionError: status message is incorrect',
'c29996019':'AssertionError: IDCS editor cells not displayed as expected',
'c12855472':'AssertionError: Date text is incorrect',
'c27276647':'AssertionError: unsigned document download text mismatch',
'c20332363':'AssertionError: signed serial approvers invoice not displayed',
'c29996034':'AssertionError: cell update affected other cells background',
'c29996033':'AssertionError: table structure incorrect after border update',
'c29986465':'AssertionError: signed subs CLW content on first draw incorrect',
'c4884125':'NoSuchElementException: report-name input not found',
'c29587349':'AttributeError: DisplayDate has no attribute french_translation',
'c1713736':'NoSuchElementException: report-name input not found',
'c29996012':'AssertionError: IDCS editor table not as expected after insert columns',
'c30029784':'AssertionError: Estimated Early Payment amount is incorrect',
'c7349961':'AttributeError: DisplayDate has no attribute french_translation',
'c660661':'StaleElementReferenceException: stale element not found in current frame',
'c13740722':'AssertionError: actual report mismatch with expected report',
'c20222880':'TimeoutException while locating element for classification tracking',
'c29484705':'AssertionError: payment records present unexpectedly',
'c7351619':'AssertionError: validation error should not be displayed',
'c30095423':'AssertionError: editor options combination not correctly applied',
'c30095425':'AssertionError: editor options combination not correctly applied',
'c30091734':'AssertionError: TPA accelerated invoices message missing',
'c20256949':'RuntimeException: multiselect options not clickable in report',
'c60752':'AssertionError: EFT file does not contain expected content',
'c2890078':'NoSuchElementException: Fees/Adjustments tab element not found',
'c29882741':'RuntimeException: generate_all_receivable_reports did not complete',
'c2889775':'RuntimeException: Confirm button was not clickable',
'c8156048':'RuntimeException: Confirm button was not clickable',
'c11925246':'NoSuchElementException: Accounts Receivables report download link not found',
'c29437393':'AssertionError: Exported records page types not correct',
'c29603047':'AssertionError: TPA meterable report mismatch',
'c29603049':'AssertionError: TPA meterable report mismatch',
'c2889831':'RuntimeException: Confirm button was not clickable',
'c30077268':'StaleElementReferenceException: stale element not found in current frame',
'c29476725':'AssertionError: Last modified text in drawer is not as expected',
'c29704023':'AssertionError: required report not present in reports list',
'c30091059':'AssertionError: Last Run Date incorrect for duplicated report',
'c16740777':'NoSuchElementException: generated report download button not found',
'c29589755':'NoSuchElementException: Assign To Org row/input not found',
'c30093314':'NoSuchElementException: Assign To Org row/input not found',
'c20991204':'StaleElementReferenceException: stale element not found in current frame',
'c8834972':'UncheckedExecutionException: IOException stream closed',
'c29988497':'UncheckedExecutionException: IOException stream closed',
'c30049539':'NoSuchElementException: project_name cell not found in fee bases table',
'c7762444':'NoSuchElementException: xls output radio input not found',
'c20256931':'RuntimeException: payment number cell not clickable',
'c14288302':'AssertionError: SR drawer project default selection incorrect',
'c29825771':'NoSuchElementException: rejectedInvoiceWarning not found',
'c279039':'NoSuchElementException: report-name input not found',
'c29595608':'NoSuchElementException: checkbox in enterprise disbursement not found',
'c2333847':'AssertionError: ibis response different than expected',
'c7349969':'AssertionError: profile update status message incorrect',
'c29996024':'RuntimeException: merge cells toolbar button not clickable',
'c29437529':'AssertionError: document not saved with expected notary variables'
}

rows_to_add = [
('c30000680','Grid','KITTEN Self-service document templates','Fixed','ICPM-72573'),('c29996023','Grid','KITTEN Self-service document templates','Fixed',''),('c29996022','Grid','KITTEN Self-service document templates','Fixed',''),('c29996030','Grid','KITTEN Self-service document templates','Fixed',''),('c29996027','Grid','KITTEN Self-service document templates','Fixed',''),('c29996028','Grid','KITTEN Self-service document templates','Fixed',''),('c29996029','Grid','KITTEN Self-service document templates','Fixed',''),('c30000681','Grid','KITTEN Self-service document templates','Fixed','ICPM-72573'),('c29996031','Grid','KITTEN Self-service document templates','Fixed',''),('c30000682','Grid','KITTEN Self-service document templates','Fixed','ICPM-72573'),('c29996021','Grid','KITTEN Self-service document templates','Fixed',''),('c29868427','Grid','KITTEN Self-service document templates','Fixed',''),('c19926499','Grid','KITTEN Self-service document templates','Fixed',''),('c29996013','Grid','KITTEN Self-service document templates','Fixed',''),('c30093696','Grid','KITTEN Self-service document templates','Fixed',''),('c29996026','Grid','KITTEN Self-service document templates','Fixed',''),('c29996032','Grid','KITTEN Self-service document templates','Fixed',''),('c879898','Grid','Translations - Canada','Fault','traceback saving edit user'),('c1119122','Grid','Contract - Usage Fees','Reliability','passed locally'),('c29647310','Grid','Enterprise Disbursement Page','Reliability','passed locally'),('c29759993','Grid','Project - Enable Owner Billing (Project General > Project Setup)','Reliability','passed locally'),('c29988497','Grid','Reports - Reportage','Reliability','passed locally'),('c29986480','Grid','DocuSign','Automation Update','test automation needs update'),('c879904','Grid','Translations - Canada','Fault',''),('c879894','Grid','Translations - Canada','Fault',''),('c879903','Grid','Translations - Canada','Fault',''),('c879901','Grid','Translations - Canada','Fault',''),('c879902','Grid','Translations - Canada','Fault',''),('c879900','Grid','Translations - Canada','Fault',''),('c879899','Grid','Translations - Canada','Fault',''),('c20904245','Grid','Administration-Messages','Fault',''),('c20904268','Grid','Administration-Messages','Fault',''),('c472573','Grid','Administration-Messages','Fault',''),('c2505467','Grid','Compliance - Legal Document','Fault',''),('c30087463','Grid','Reports - Reportage','Automation Update',''),('c30095456','Grid','Reports - Reportage','Automation Update',''),('c29647235','Grid','Enterprise Disbursement Page','Reliability','passed locally'),('c8370199','Grid','Draw - Draw','Automation Update',''),('c29986467','Grid','DocuSign','Fixed','one variable was pushed to next page'),('c30096980','Grid','Reports - Reportage','Automation Update',''),('c879897','Grid','Translations - Canada','Fault',''),('c18205514','Grid','Reports - Reportage','Automation Update',''),('c29986466','Grid','DocuSign','Automation Update','wrong document returned during execution'),('c15724980','Grid','Administration-Messages','Fault',''),('c27276649','Grid','Documents','Fixed','AUR fixed'),('c1156161','Grid','Contract - Usage Fees','Reliability','feebill fees ended up showing after waiting long enough'),('c29995857','Grid','KITTEN Self-service document templates','Automation Update','merge issue due to kitten table improvements'),('c209985','Grid','Administration-Messages','Fault','ICPM-72571'),('c29996019','Grid','KITTEN Self-service document templates','Automation Update','merge issue due to kitten table improvements'),('c12855472','Grid','Administration-Messages','Reliability','works when hour is 01-11 which makes testcases flaky. fixed by updated to 01-12 as expected'),('c27276647','Grid','Documents','Fixed','AUR fixed'),('c20332363','Grid','Documents','Fixed','AUR fixed'),('c29996034','Grid','KITTEN Self-service document templates','Automation Update','merge issue due to kitten table improvements'),('c29996033','Grid','KITTEN Self-service document templates','Automation Update','merge issue due to kitten table improvements'),('c29986465','Grid','DocuSign','Fixed','one variable was pushed to next page'),('c4884125','Grid','Compliance - Legal Document','Fault','clicking continue button on CreateReport page was happening to fast back to back, and not letting the page settle'),('c29587349','Grid','Administration - System (Rename: Account Setup)','Fault',''),('c1713736','Grid','Interface - Standard Web Services','Reliability','Passed Locally'),('c29996012','Grid','KITTEN Self-service document templates','Reliability','Fails in Prod as well'),('c30029784','Grid','Organization - Textura Payment Accelerator (TPA)','Fault',''),('c7349961','Grid','Internal - Pronto Signature System (Rename?)','Fault',''),('c660661','Grid','Invoice - Tax','Reliability','Passed locally'),('c13740722','Grid','Organization - Project Supplier Tracking','Fault',''),('c20222880','Grid','Organization - Project Supplier Tracking','Fault',''),('c29995861','Grid','KITTEN Self-service document templates','Reliability','Passed Locally'),('c29484705','Grid','Project - Project Fees','Automation Update','AUR Raised'),('c7351619','Grid','Internal - Pronto Signature System (Rename?)','Fault',''),('c29595608','Grid','Interface - eBIS','Reliability','Passed Locally'),('c2333847','Grid','Project - CPM Fee Sales Tax calculation (CPM-10077)','Fault',''),('c7349969','Grid','Internal - Pronto Signature System (Rename?)','Fault',''),('c30095423','Grid','KITTEN Self-service document templates','Fixed','ICPM-72573'),('c30095425','Grid','KITTEN Self-service document templates','Fixed','ICPM-72573'),('c30091734','External','Organization - Textura Payment Accelerator (TPA)','Automation Update',''),('c20256949','External','Reports - Reportage','Automation Update',''),('c60752','DTC','Internal - PDQBach','Reliability','possible prod issue'),('c2890078','DTC','Internal - FeeBill','Reliability','prod failure'),('c29882741','DTC','Organization - Textura Payment Accelerator (TPA)','Reliability','prod failure'),('c2889775','DTC','Internal - FeeBill','Reliability','passed on dtc rerun'),('c8156048','DTC','Internal - FeeBill','Reliability','passed on dtc rerun'),('c11925246','DTC','Internal - FeeBill','Reliability','passed on dtc rerun'),('c29437393','DTC','Interface - CSVus2','Reliability','passed on dtc rerun'),('c29603047','DTC','Internal - FeeBill','Fixed',''),('c29603049','DTC','Internal - FeeBill','Fixed',''),('c2889831','DTC','Internal - FeeBill','Reliability','passed on dtc rerun'),('c29996012','Grid','KITTEN Self-service document templates','Automation Update',''),('c30077268','Grid','Compliance - Lien Waiver','Reliability','Fails in Proda as well'),('c29476725','Grid','Project - General','Reliability','Passed locally'),('c29704023','Grid','Reports - Reportage','Automation Update','ICPM-72652'),('c30091059','Grid','Reports - Reportage','Automation Update','ICPM-72653'),('c30029784','Grid','Organization - Textura Payment Accelerator (TPA)','Fault','ICPM-72586'),('c16740777','Grid','Draw - Track Draw Deadlines','Reliability','passed locally'),('c29589755','Grid','KITTEN Self-service document templates','Reliability','passed locally, tar took too long to upload'),('c30093314','Grid','KITTEN Self-service document templates','Reliability','passed locally, tar took too long to upload'),('c29986466','Grid','DocuSign','Automation Update','due to change in editor while copying curated template'),('c29986480','Grid','DocuSign','Automation Update','due to change in editor while copying curated template'),('c29996019','Grid','KITTEN Self-service document templates','Automation Update','due to change in editor table'),('c27276647','Grid','Documents','Reliability','passed locally'),('c29996024','Grid','KITTEN Self-service document templates','Reliability','passed locally, merging cells need more time'),('c13740722','Grid','Organization - Project Supplier Tracking','Automation Update',''),('c20991204','Grid','Contract - Contract Status','Reliability','Fails in Prod as well'),('c8834972','Grid','Interface - Java Client','Reliability','Passed Locally'),('c29988497','Grid','Reports - Reportage','Reliability','Passed locally'),('c29647310','Grid','Enterprise Disbursement Page','Reliability','Passed Locally'),('c30049539','Grid','Internal - FeeBill','Reliability','Fails in Prod as well'),('c7762444','Grid','Compliance - Legal Document','Reliability','Passed Locally'),('c20256931','Grid','Organization - Manage Owner Funding','Reliability','Fails from Prod as well'),('c14288302','Grid','Administration - System (Rename: Account Setup)','Reliability','Fails in Prod as well'),('c29825771','Grid','Draw - Close Draw (move to Draw - Draw)','Reliability','Passed locally'),('c279039','Grid','Compliance - Legal Document','Reliability','Passed Locally'),('c1713736','Grid','Interface - Standard Web Services','Reliability','Passed Locally'),('c29437529','Grid','KITTEN Self-service document templates','Reliability','passed locally')
]

with csv_path.open('a', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    for tcid, tctype, suite, status, comments in rows_to_add:
        w.writerow([tcid, tctype, suite, status, comments, exception_map.get(tcid, 'No exception in extract (passed/comment based)')])

print('Appended', len(rows_to_add), 'rows')
